package com.yahala.SQLite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CHAT_SETTINGS.
 */
public class ChatSettings {

    private String jid;
    private byte[] participants;

    public ChatSettings() {
    }

    public ChatSettings(String jid, byte[] participants) {
        this.jid = jid;
        this.participants = participants;
    }

    public String getJid() {
        return jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

    public byte[] getParticipants() {
        return participants;
    }

    public void setParticipants(byte[] participants) {
        this.participants = participants;
    }

}
