package com.yahala.SQLite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yahala.SQLite.UserSetting;
import com.yahala.SQLite.Messages;
import com.yahala.SQLite.Contacts;
import com.yahala.SQLite.Chats;
import com.yahala.SQLite.ChatSettings;
import com.yahala.SQLite.Wallpapers;
import com.yahala.SQLite.Groups;

import com.yahala.SQLite.UserSettingDao;
import com.yahala.SQLite.MessagesDao;
import com.yahala.SQLite.ContactsDao;
import com.yahala.SQLite.ChatsDao;
import com.yahala.SQLite.ChatSettingsDao;
import com.yahala.SQLite.WallpapersDao;
import com.yahala.SQLite.GroupsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userSettingDaoConfig;
    private final DaoConfig messagesDaoConfig;
    private final DaoConfig contactsDaoConfig;
    private final DaoConfig chatsDaoConfig;
    private final DaoConfig chatSettingsDaoConfig;
    private final DaoConfig wallpapersDaoConfig;
    private final DaoConfig groupsDaoConfig;

    private final UserSettingDao userSettingDao;
    private final MessagesDao messagesDao;
    private final ContactsDao contactsDao;
    private final ChatsDao chatsDao;
    private final ChatSettingsDao chatSettingsDao;
    private final WallpapersDao wallpapersDao;
    private final GroupsDao groupsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userSettingDaoConfig = daoConfigMap.get(UserSettingDao.class).clone();
        userSettingDaoConfig.initIdentityScope(type);

        messagesDaoConfig = daoConfigMap.get(MessagesDao.class).clone();
        messagesDaoConfig.initIdentityScope(type);

        contactsDaoConfig = daoConfigMap.get(ContactsDao.class).clone();
        contactsDaoConfig.initIdentityScope(type);

        chatsDaoConfig = daoConfigMap.get(ChatsDao.class).clone();
        chatsDaoConfig.initIdentityScope(type);

        chatSettingsDaoConfig = daoConfigMap.get(ChatSettingsDao.class).clone();
        chatSettingsDaoConfig.initIdentityScope(type);

        wallpapersDaoConfig = daoConfigMap.get(WallpapersDao.class).clone();
        wallpapersDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        userSettingDao = new UserSettingDao(userSettingDaoConfig, this);
        messagesDao = new MessagesDao(messagesDaoConfig, this);
        contactsDao = new ContactsDao(contactsDaoConfig, this);
        chatsDao = new ChatsDao(chatsDaoConfig, this);
        chatSettingsDao = new ChatSettingsDao(chatSettingsDaoConfig, this);
        wallpapersDao = new WallpapersDao(wallpapersDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);

        registerDao(UserSetting.class, userSettingDao);
        registerDao(Messages.class, messagesDao);
        registerDao(Contacts.class, contactsDao);
        registerDao(Chats.class, chatsDao);
        registerDao(ChatSettings.class, chatSettingsDao);
        registerDao(Wallpapers.class, wallpapersDao);
        registerDao(Groups.class, groupsDao);
    }

    public void clear() {
        userSettingDaoConfig.getIdentityScope().clear();
        messagesDaoConfig.getIdentityScope().clear();
        contactsDaoConfig.getIdentityScope().clear();
        chatsDaoConfig.getIdentityScope().clear();
        chatSettingsDaoConfig.getIdentityScope().clear();
        wallpapersDaoConfig.getIdentityScope().clear();
        groupsDaoConfig.getIdentityScope().clear();
    }

    public UserSettingDao getUserSettingDao() {
        return userSettingDao;
    }

    public MessagesDao getMessagesDao() {
        return messagesDao;
    }

    public ContactsDao getContactsDao() {
        return contactsDao;
    }

    public ChatsDao getChatsDao() {
        return chatsDao;
    }

    public ChatSettingsDao getChatSettingsDao() {
        return chatSettingsDao;
    }

    public WallpapersDao getWallpapersDao() {
        return wallpapersDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

}
