package com.yahala.SQLite;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.yahala.SQLite.Groups;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table GROUPS.
 */
public class GroupsDao extends AbstractDao<Groups, Void> {

    public static final String TABLENAME = "GROUPS";

    /**
     * Properties of entity Groups.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Jid = new Property(0, String.class, "jid", false, "JID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Participants = new Property(2, byte[].class, "participants", false, "PARTICIPANTS");
    }

    ;


    public GroupsDao(DaoConfig config) {
        super(config);
    }

    public GroupsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'GROUPS' (" + //
                "'JID' TEXT," + // 0: jid
                "'NAME' TEXT," + // 1: name
                "'PARTICIPANTS' BLOB);"); // 2: participants
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        try {
            String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GROUPS'";
            db.execSQL(sql);
        } catch (Exception e) {
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Groups entity) {
        stmt.clearBindings();

        String jid = entity.getJid();
        if (jid != null) {
            stmt.bindString(1, jid);
        }

        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }

        byte[] participants = entity.getParticipants();
        if (participants != null) {
            stmt.bindBlob(3, participants);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Groups readEntity(Cursor cursor, int offset) {
        Groups entity = new Groups( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // jid
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
                cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2) // participants
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Groups entity, int offset) {
        entity.setJid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setParticipants(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Void updateKeyAfterInsert(Groups entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Void getKey(Groups entity) {
        return null;
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
