package com.yahala.SQLite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table GROUPS.
 */
public class Groups {

    private String jid;
    private String name;
    private byte[] participants;

    public Groups() {
    }

    public Groups(String jid, String name, byte[] participants) {
        this.jid = jid;
        this.name = name;
        this.participants = participants;
    }

    public String getJid() {
        return jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getParticipants() {
        return participants;
    }

    public void setParticipants(byte[] participants) {
        this.participants = participants;
    }

}
