package com.yahala.SQLite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.yahala.messenger.TLRPC;

/**
 * Entity mapped to table MESSAGES.
 */
public class Messages {
    public TLRPC.Message tl_message;
    public TLRPC.User user;
    public int id;
    public int contentType;
    private Long ids;
    private String jid;
    private String message;
    private Integer read_state;
    private Integer send_state;
    private java.util.Date date;
    private Integer out;
    private Integer type;
    private Integer ttl;
    private byte[] data;

    public Messages() {
    }

    public Messages(Long id) {
        this.ids = id;
    }

    public Messages(Long id, String jid, String message, Integer read_state, Integer send_state, java.util.Date date, Integer out, Integer type, Integer ttl, byte[] data) {
        this.ids = id;
        this.jid = jid;
        this.message = message;
        this.read_state = read_state;
        this.send_state = send_state;
        this.date = date;
        this.out = out;
        this.type = type;
        this.ttl = ttl;
        this.data = data;
    }

    public Long getId() {
        return ids;
    }

    public void setId(Long id) {
        this.ids = id;
    }

    public String getJid() {
        return jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getRead_state() {
        return read_state;
    }

    public void setRead_state(Integer read_state) {
        this.read_state = read_state;
    }

    public Integer getSend_state() {
        return send_state;
    }

    public void setSend_state(Integer send_state) {
        this.send_state = send_state;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getOut() {
        return out;
    }

    public void setOut(Integer out) {
        this.out = out;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getTtl() {
        return ttl;
    }

    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

}
