package com.yahala.SQLite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table WALLPAPERS.
 */
public class Wallpapers {

    private Long id;
    private byte[] data;

    public Wallpapers() {
    }

    public Wallpapers(Long id) {
        this.id = id;
    }

    public Wallpapers(Long id, byte[] data) {
        this.id = id;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getData() {
        return data;
    }

    public void setData(byte[] data) {
        this.data = data;
    }

}
